version: '3.8'  # Specify the Docker Compose file format version

services:
  immich_server:
    image: ghcr.io/immich-app/immich-server:release
    ports:
      - "2283:2283"
    command: ["tini", "--", "/bin/bash", "s..."]

  immich_redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  immich_postgres:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    ports:
      - "5432:5432"

  immich_machine_learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    command: ["tini", "--", "./start.sh"]

  autoheal:
    image: willfarrell/autoheal:latest

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    ports:
      - "8080:8080"

  transmission:
    image: linuxserver/transmission:latest
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413/udp"

  bazarr:
    image: linuxserver/bazarr:latest
    ports:
      - "6767:6767"

  dozzle:
    image: amir20/dozzle:latest
    ports:
      - "8888:8080"

  librespeed:
    image: linuxserver/librespeed:latest
    ports:
      - "32768:80"
      - "443:443"

  jellyfin:
    image: linuxserver/jellyfin:latest
    ports:
      - "8096:8096"
      - "8920:8920"

  radarr:
    image: ghcr.io/hotio/radarr:latest
    ports:
      - "7878:7878"

  sonarr:
    image: linuxserver/sonarr:latest
    ports:
      - "8989:8989"

  portainer:
    image: portainer/portainer-ee:latest
    ports:
      - "8000:8000"
      - "9443:9443"
      - "9000:9000"

  lidarr:
    image: hotio/lidarr:release
    ports:
      - "8686:8686"

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:latest
    ports:
      - "9696:9696"

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    ports:
      - "5055:5055"

  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "67:67/udp"
      - "1010:80"
      - "4443:443"

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    ports:
      - "8191:8191"
      - "8192:8192"

  watchtower:
    image: containrrr/watchtower:latest
    ports:
      - "8080:8080"

# Optionally, you can define volumes, networks, and other configurations as needed

